mutation giftCardCreate($input: GiftCardCreateInput!) {
    giftCardCreate(input: $input) {
        giftCard {
            id
            initialValue {
                amount
            }
        }
        userErrors {
            message
            field
            code
        }
    }
}
