query getOrder($id: ID!) {
    order(id: $id) {
        id
        name
        processedAt
        customAttributes {
            key
            value
        }
        phone
        customer {
            id
            displayName
            email
            firstName
            lastName
            tags
            defaultAddress {
                address1
                address2
                phone
                city
                province
                provinceCode
                country
                countryCodeV2
                zip
            }
        }
        lineItems(first: 100) {
            edges {
                node {
                    quantity
                    sku
                    product {
                        id
                        title
                    }
                    variant {
                        id
                        title
                        sku
                    }
                }
            }
        }
    }
}
