query getProduct($id: ID!) {
    product(id: $id) {
        id
        title
        handle
        description
        descriptionHtml
        variants(first: 20) {
            edges {
                node {
                    id
                    title
                    price
                    sku
                    image {
                        id
                        url
                    }
                    availableForSale
                    inventoryQuantity
                    variantDescription: metafield(namespace: "custom", key: "variant_description") {
                        value
                    }
                }
            }
        }
        images(first: 5) {
            edges {
                node {
                    id
                    src
                    altText
                }
            }
        }
    }
}
