mutation addCartLines($cartId: ID!, $lines: [CartLineInput!]!) {
    cartLinesAdd(cartId: $cartId, lines: $lines) {
        cart {
            id
            checkoutUrl
            lines(first: 5) {
                edges {
                    node {
                        id
                    }
                }
            }
        }
        userErrors {
            field
            message
        }
    }
}
