mutation removeCartLines($cartId: ID!, $lineIds: [ID!]!) {
    cartLinesRemove(cartId: $cartId, lineIds: $lineIds) {
        cart {
            id
            checkoutUrl
            lines(first: 5) {
                edges {
                    node {
                        id
                    }
                }
            }
        }
        userErrors {
            field
            message
        }
    }
}
